DROP TABLE IF EXISTS TECHNICALPROOF_PRODUCTS;
DROP TABLE IF EXISTS TECHNICALPROOF_GROUPS;
------------------
--CREATE SCHEMA---
------------------
CREATE TABLE TECHNICALPROOF_GROUPS(
	GROUP_ID INT,
	GROUP_NAME VARCHAR(255),
	CONSTRAINT pk_tpg PRIMARY KEY(GROUP_ID)
);

CREATE TABLE TECHNICALPROOF_PRODUCTS(
	BRAND_ID INT,
	START_DATE DATETIME,
	END_DATE DATETIME,
	PRICE_LIST INT,
	PRODUCT_ID INT,
	PRIORITY INT,
	PRICE DECIMAL(10,2),
	CURR VARCHAR(3),
	CONSTRAINT fk_tpp_tpg FOREIGN KEY (BRAND_ID) REFERENCES TECHNICALPROOF_GROUPS(GROUP_ID),
	CONSTRAINT pk_tpp PRIMARY KEY(PRICE_LIST,PRODUCT_ID)
);
